name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Запускаем только при изменениях в ветке main
  workflow_dispatch:

# Права доступа для публикации на GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Отмена предыдущих запусков для этого же коммита
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Firebase Tools больше не нужны
          # npm install -g firebase-tools

      - name: Generate Site
        env:
          # Секрет Firebase больше не нужен, но оставляем на случай, если скрипт его требует
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_RAZRABOTKA }}
        run: python generate_site.py

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Загружаем содержимое папки public, где лежит сгенерированный сайт
          path: './public'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
